---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-

bases:
- ../../base

namespace: prod-coffeeshop

patches:
- ./deployment-patches.yaml
- ./route-patches.yaml
- ./service-patches.yaml

configMapGenerator:
- name: coffee-shop
  envs:
  - ./configmap.env

