---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namePrefix: prod-
nameSuffix: -prod

bases:
- ../../base

namespace: my-kafka-project-prod

patches:
- ./kafka-patches.yaml

configMapGenerator:
#- name: coffee-shop
#  envs:
#  - ./configmap.env

