apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-producer
  name: kafka-producer
  namespace: my-pro-con-project
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka-producer
  template:
    metadata:
      labels:
        name: kafka-producer
    spec:
      containers:
      - name: kafka-producer
        image: strimzi/hello-world-producer:latest
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 1Gi
        env:
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap.my-kafka-project.svc.cluster.local:9092
          - name: TOPIC
            value: my-topic
          - name: DELAY_MS
            value: "1000"
          - name: LOG_LEVEL
            value: "INFO"
          - name: MESSAGE_COUNT
            value: "1000"
