apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-consumer-2
  name: kafka-consumer-2
  namespace: my-pro-con-project
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka-consumer-2
  template:
    metadata:
      labels:
        name: kafka-consumer-2
    spec:
      containers:
      - name: kafka-consumer
        image: strimzi/hello-world-consumer:latest
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 1Gi
        env:
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap.my-kafka-project.svc.cluster.local:9092
          - name: TOPIC
            value: my-topic
          - name: GROUP_ID
            value: my-hello-world-consumer
          - name: LOG_LEVEL
            value: "INFO"
          - name: MESSAGE_COUNT
            value: "1000"
