apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kafka-cluster-dr
  namespace: openshift-gitops
spec:
  description: Kafka cluster for DR
  destinations:
  - namespace: my-kafka-dr-project
    server: https://kubernetes.default.svc
#  namespaceResourceBlacklist:
#  - group: tekton.dev
#    kind: '*'
#  - group: triggers.tekton.dev
#    kind: '*'
  sourceRepos:
  - https://github.com/suzukiry/kafka-strimzi.git

