apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
 name: my-connect-cluster
 namespace: my-kafka-project
 annotations:
   strimzi.io/use-connector-resources: "true"

spec:
  bootstrapServers: my-cluster-kafka-bootstrap:9092
  version: 2.8.0
  replicas: 1
  resources:
    requests:
      memory: 512Mi
      cpu: 200m
    limits:
      memory: 2Gi
      cpu: 500m
  readinessProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 5
  livenessProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 5
  config:
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false
